//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUpdate
    {
        public long Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime FromDate { get; set; }
        public string FileAddress { get; set; }
        public System.DateTime ToDate { get; set; }
        public bool IsActive { get; set; }
        public double Version { get; set; }
        public string Description { get; set; }
        public bool IsForced { get; set; }
    }
}
