//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KonkorEntities2 : DbContext
    {
        public KonkorEntities2()
            : base("name=KonkorEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AppUpdate> AppUpdates { get; set; }
        public virtual DbSet<BookName> BookNames { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<DeviceInformation> DeviceInformations { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<ExamDetail> ExamDetails { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<Queue> Queues { get; set; }
        public virtual DbSet<ReferenceQuestion> ReferenceQuestions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<SubscriberPermission> SubscriberPermissions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TextBook> TextBooks { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ExamTest> ExamTests { get; set; }
        public virtual DbSet<ExamTestQuestion> ExamTestQuestions { get; set; }
    }
}
