//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceInformation
    {
        public long Id { get; set; }
        public string Brand { get; set; }
        public string Device { get; set; }
        public string Model { get; set; }
        public string Product { get; set; }
        public string SDK { get; set; }
        public string Realease { get; set; }
        public string Incrimental { get; set; }
        public long Device_Id { get; set; }
    
        public virtual Device Device1 { get; set; }
    }
}
