//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTestQuestion
    {
        public long Id { get; set; }
        public Nullable<long> ExamTestId { get; set; }
        public Nullable<long> QuestionId { get; set; }
    }
}
