//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTest
    {
        public long Id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<long> FieldId { get; set; }
        public Nullable<long> GradeId { get; set; }
        public Nullable<long> BookNameId { get; set; }
        public Nullable<long> LessonId { get; set; }
        public Nullable<long> TopicId { get; set; }
        public Nullable<int> Hardness { get; set; }
    }
}
