//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamDetail
    {
        public long Id { get; set; }
        public long Exam_Id { get; set; }
        public long BookName_Id { get; set; }
        public Nullable<long> Lesson_Id { get; set; }
        public Nullable<long> Topic_Id { get; set; }
        public Nullable<int> Accsept { get; set; }
        public Nullable<int> Wrong { get; set; }
        public long CreatorSubscriber_Id { get; set; }
    
        public virtual BookName BookName { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
