//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime ExpireTime { get; set; }
        public System.DateTime UseTime { get; set; }
        public Nullable<long> Field_Id { get; set; }
        public Nullable<long> Grade_Id { get; set; }
        public Nullable<long> BookName_Id { get; set; }
        public Nullable<long> Lesson_Id { get; set; }
        public Nullable<long> Topic_Id { get; set; }
    }
}
