//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PathKey { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> Day { get; set; }
        public System.DateTime InsertDate { get; set; }
        public long InsertUser_Id { get; set; }
        public long Answer_Id { get; set; }
        public long Topic_Id { get; set; }
        public long SubscriberAcc { get; set; }
        public long SubscriberCount { get; set; }
        public long SubscriberWrong { get; set; }
        public double FuzzyValue { get; set; }
        public int EstimateTime { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<long> UpdateUser_Id { get; set; }
        public long ReferenceQuestion_Id { get; set; }
        public string Code { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual ReferenceQuestion ReferenceQuestion { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
