//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberPermission
    {
        public long Id { get; set; }
        public long Subscriber_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> AnswerPer { get; set; }
        public Nullable<long> TextBookPer { get; set; }
        public Nullable<long> GradePer { get; set; }
        public Nullable<long> LessonPer { get; set; }
        public Nullable<long> FieldPer { get; set; }
        public Nullable<long> BookNamePer { get; set; }
        public Nullable<long> TopicPer { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime RoleExpireDate { get; set; }
        public Nullable<long> Package_Id { get; set; }
        public Nullable<bool> AutoExtend { get; set; }
    
        public virtual Subscriber Subscriber { get; set; }
    }
}
