//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextBook
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PathKey { get; set; }
        public bool IsDraft { get; set; }
        public long Day { get; set; }
        public long ContentType_Id { get; set; }
        public System.DateTime InsertDate { get; set; }
        public long InsertUser_Id { get; set; }
        public long Grade_Id { get; set; }
        public long Lesson_Id { get; set; }
        public long Field_Id { get; set; }
        public long BookName_Id { get; set; }
        public long Topic_Id { get; set; }
        public bool IsActive { get; set; }
        public long SubscriberViewCount { get; set; }
        public Nullable<double> FuzzyValueToRead { get; set; }
        public Nullable<int> EstimateTimeRead { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<long> UpdateUser_Id { get; set; }
    
        public virtual BookName BookName { get; set; }
        public virtual Field Field { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
